server:
    port: 8080
spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: July750113
        url: jdbc:mysql://localhost:3306/estudio_juridico
        username: root
    jpa:
        hibernate:
            ddl-auto: update